const $=(s)=>document.querySelector(s);
const fileInput=$("#file-input"),dropZone=$("#drop-zone"),statusPill=$("#status-pill"),transcriptInput=$("#transcript-input"),segmentCount=$("#segment-count"),segmentTable=$("#segment-table"),downloadJson=$("#download-json"),downloadCard=$("#download-card");
const canvases={waveform:$("#waveform-canvas"),spectrogram:$("#spectrogram-canvas"),mfcc:$("#mfcc-canvas")};
const meta={fileName:$("#file-name"),duration:$("#duration"),sampleRate:$("#sample-rate"),channels:$("#channels"),rms:$("#rms"),f0:$("#f0"),boundaryCount:$("#boundary-count"),moraCount:$("#mora-count")};
const FFT_SIZE=2048,HOP_SIZE=512,MEL_BANDS=40,MFCC_COUNT=20,MAX_AUDIO_SECONDS=30;
const SMALL_KANA=new Set(["\u3083","\u3085","\u3087","\u30e3","\u30e5","\u30e7"]),STANDALONE_MORA=new Set(["\u3063","\u30c3","\u30fc"]);
const TOKEN_LABELS=new Map([["\u3042","a"],["\u3044","i"],["\u3046","u"],["\u3048","e"],["\u304a","o"],["\u30a2","a"],["\u30a4","i"],["\u30a6","u"],["\u30a8","e"],["\u30aa","o"]]);
let currentAudio=null,currentExperiment=null;
function setStatus(text,state=""){statusPill.textContent=text;statusPill.className=`status-pill ${state}`.trim()}
function formatDuration(seconds){if(!Number.isFinite(seconds))return"-";const m=Math.floor(seconds/60),r=seconds-m*60;return`${m}:${r.toFixed(2).padStart(5,"0")}`}
function splitMora(text){const out=[];for(const ch of Array.from(text.replace(/\s+/g,""))){if(SMALL_KANA.has(ch)&&out.length&&!STANDALONE_MORA.has(out[out.length-1]))out[out.length-1]+=ch;else out.push(ch)}return out}
function tokenizeTranscript(text){return splitMora(text).map(token=>({token,label:TOKEN_LABELS.get(token)||token.toLowerCase()}))}
function mixToMono(buffer){const mono=new Float32Array(buffer.length);for(let c=0;c<buffer.numberOfChannels;c++){const data=buffer.getChannelData(c);for(let i=0;i<buffer.length;i++)mono[i]+=data[i]/buffer.numberOfChannels}return mono}
function rms(samples,start=0,end=samples.length){const from=Math.max(0,Math.floor(start)),to=Math.min(samples.length,Math.max(from+1,Math.floor(end)));let sum=0;for(let i=from;i<to;i++)sum+=samples[i]**2;return Math.sqrt(sum/(to-from))}
function zcr(samples){let n=0;for(let i=1;i<samples.length;i++)if((samples[i-1]>=0&&samples[i]<0)||(samples[i-1]<0&&samples[i]>=0))n++;return n/Math.max(1,samples.length-1)}
function mean(values){const clean=values.filter(Number.isFinite);return clean.length?clean.reduce((a,b)=>a+b,0)/clean.length:0}
function estimateF0(samples,sr,start=0,end=samples.length){const from=Math.max(0,Math.floor(start)),to=Math.min(samples.length,Math.max(from+1,Math.floor(end))),maxSamples=Math.min(to-from,Math.floor(sr*1.5));if(maxSamples<sr*0.03)return null;const data=samples.slice(from,from+maxSamples);if(rms(data)<0.005)return null;const minLag=Math.floor(sr/500),maxLag=Math.min(Math.floor(sr/50),data.length-1),corr=[];let best=-Infinity;for(let lag=minLag;lag<=maxLag;lag++){let c=0;for(let i=0;i<data.length-lag;i++)c+=data[i]*data[i+lag];c/=data.length-lag;corr[lag]=c;if(c>best)best=c}if(best<=0)return null;const threshold=best*0.82;for(let lag=minLag+1;lag<maxLag;lag++)if(corr[lag]>=threshold&&corr[lag]>=corr[lag-1]&&corr[lag]>=corr[lag+1])return sr/lag;return null}
function hann(size){const w=new Float32Array(size);for(let i=0;i<size;i++)w[i]=0.5-0.5*Math.cos(2*Math.PI*i/(size-1));return w}
function fftMagnitudes(frame){const n=frame.length,real=Float64Array.from(frame),imag=new Float64Array(n);for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[real[i],real[j]]=[real[j],real[i]];[imag[i],imag[j]]=[imag[j],imag[i]]}}for(let len=2;len<=n;len<<=1){const angle=-2*Math.PI/len,wr0=Math.cos(angle),wi0=Math.sin(angle);for(let i=0;i<n;i+=len){let wr=1,wi=0;for(let j=0;j<len/2;j++){const ur=real[i+j],ui=imag[i+j],vr=real[i+j+len/2]*wr-imag[i+j+len/2]*wi,vi=real[i+j+len/2]*wi+imag[i+j+len/2]*wr;real[i+j]=ur+vr;imag[i+j]=ui+vi;real[i+j+len/2]=ur-vr;imag[i+j+len/2]=ui-vi;const nr=wr*wr0-wi*wi0;wi=wr*wi0+wi*wr0;wr=nr}}}const out=new Float32Array(n/2);for(let i=0;i<out.length;i++)out[i]=Math.hypot(real[i],imag[i]);return out}
function createFrames(samples){const w=hann(FFT_SIZE),frames=[];for(let start=0;start+FFT_SIZE<=samples.length;start+=HOP_SIZE){const frame=new Float32Array(FFT_SIZE);for(let i=0;i<FFT_SIZE;i++)frame[i]=samples[start+i]*w[i];frames.push(fftMagnitudes(frame))}return frames.length?frames:[fftMagnitudes(padShortAudio(samples))]}
function centroid(mags,sr){let weighted=0,total=0;for(let i=0;i<mags.length;i++){weighted+=(i*sr/FFT_SIZE)*mags[i];total+=mags[i]}return total?weighted/total:0}
function createAnalysisFrames(samples,sr){const frames=[];for(let start=0;start+FFT_SIZE<=samples.length;start+=HOP_SIZE){const raw=samples.slice(start,start+FFT_SIZE),mags=fftMagnitudes(raw);frames.push({startSample:start,startTime:start/sr,endTime:Math.min(samples.length,start+FFT_SIZE)/sr,centerTime:(start+FFT_SIZE/2)/sr,rms:rms(raw),zcr:zcr(raw),spectralCentroid:centroid(mags,sr),magnitudes:mags})}if(!frames.length){const padded=padShortAudio(samples),mags=fftMagnitudes(padded);frames.push({startSample:0,startTime:0,endTime:samples.length/sr,centerTime:samples.length/sr/2,rms:rms(samples),zcr:zcr(samples),spectralCentroid:centroid(mags,sr),magnitudes:mags})}const mfccs=computeMfcc(frames.map(f=>f.magnitudes),sr);frames.forEach((f,i)=>f.mfcc=mfccs[i]);return frames}
function hzToMel(hz){return 2595*Math.log10(1+hz/700)}function melToHz(mel){return 700*(10**(mel/2595)-1)}
function melFilterbank(sr,bins){const min=hzToMel(0),max=hzToMel(sr/2),points=Array.from({length:MEL_BANDS+2},(_,i)=>melToHz(min+(max-min)*i/(MEL_BANDS+1))),idx=points.map(hz=>Math.floor((FFT_SIZE+1)*hz/sr));return Array.from({length:MEL_BANDS},(_,m)=>{const f=new Float32Array(bins);for(let k=idx[m];k<idx[m+1]&&k<bins;k++)f[k]=(k-idx[m])/Math.max(1,idx[m+1]-idx[m]);for(let k=idx[m+1];k<idx[m+2]&&k<bins;k++)f[k]=(idx[m+2]-k)/Math.max(1,idx[m+2]-idx[m+1]);return f})}
function computeMfcc(frames,sr){const filters=melFilterbank(sr,frames[0]?.length||FFT_SIZE/2);return frames.map(mags=>{const mel=filters.map(filter=>{let e=0;for(let i=0;i<filter.length;i++)e+=(mags[i]**2)*filter[i];return Math.log(Math.max(e,1e-12))});return Array.from({length:MFCC_COUNT},(_,k)=>mel.reduce((sum,v,n)=>sum+v*Math.cos(Math.PI*k*(n+0.5)/MEL_BANDS),0))})}
function avgMfcc(frames){const sums=new Array(MFCC_COUNT).fill(0);for(const f of frames)for(let i=0;i<MFCC_COUNT;i++)sums[i]+=f[i]||0;return sums.map(v=>v/Math.max(1,frames.length))}
function vdist(a=[],b=[]){const n=Math.min(a.length,b.length);let s=0;for(let i=0;i<n;i++)s+=(a[i]-b[i])**2;return n?Math.sqrt(s/n):0}
function scoreBoundaryCandidates(frames,duration){const rmsMax=Math.max(...frames.map(f=>f.rms),1e-8),centMax=Math.max(...frames.map(f=>f.spectralCentroid),1e-8),c=[];for(let i=1;i<frames.length;i++){const p=frames[i-1],f=frames[i],low=1-Math.min(1,(p.rms+f.rms)/2/rmsMax),sil=p.rms<rmsMax*.12||f.rms<rmsMax*.12?1:0,drop=Math.max(0,p.rms-f.rms)/rmsMax,md=vdist(p.mfcc,f.mfcc)/80,cd=Math.abs(f.spectralCentroid-p.spectralCentroid)/centMax,score=low*.35+sil*.25+drop*.15+md*.15+cd*.1;c.push({time:f.startTime,score,lowEnergy:low,rmsDrop:drop,mfccDelta:md,centroidDelta:cd,isPeak:false})}for(let i=1;i<c.length-1;i++)c[i].isPeak=c[i].score>=c[i-1].score&&c[i].score>=c[i+1].score&&c[i].score>.28;return[{time:0,score:1,isPeak:true},...c.filter(x=>x.time>.04&&x.time<duration-.04),{time:duration,score:1,isPeak:true}]}
function alignBoundaries(candidates,count,duration){if(count<=0)return[0,duration];if(count===1)return[0,duration];const minSeg=Math.max(.04,duration/count*.35),usable=candidates.filter(c=>c.time>minSeg&&c.time<duration-minSeg).map(c=>({...c,score:c.score+(c.isPeak?0.18:0)})),chosen=[];for(let slot=1;slot<count;slot++){const target=duration*slot/count,width=duration/count;let best=null,bestVal=-Infinity;for(const c of usable){if(chosen.includes(c))continue;const times=[...chosen.map(x=>x.time),c.time].sort((a,b)=>a-b);if(!times.every((t,i)=>i===0||t-times[i-1]>=minSeg))continue;const val=c.score-Math.abs(c.time-target)/width*.32;if(val>bestVal){best=c;bestVal=val}}chosen.push(best||{time:target,score:0,interpolated:true})}return repairBoundaries([0,...chosen.map(c=>c.time).sort((a,b)=>a-b),duration],count,duration)}
function repairBoundaries(boundaries,count,duration){const out=[0];for(let i=1;i<count;i++){const fallback=duration*i/count,value=Number.isFinite(boundaries[i])?boundaries[i]:fallback;out.push(Math.max(out[i-1]+.02,Math.min(duration-.02*(count-i),value)))}out.push(duration);return out}
function extractSegmentFeatures(samples,sr,duration,tokens){if(!tokens.length)return{segments:[],boundaries:[0,duration],candidateCount:0};const analysis=createAnalysisFrames(samples,sr),candidates=scoreBoundaryCandidates(analysis,duration),boundaries=alignBoundaries(candidates,tokens.length,duration);const segments=tokens.map(({token,label},i)=>{const startTime=boundaries[i],endTime=boundaries[i+1],startSample=Math.floor(startTime*sr),endSample=Math.min(samples.length,Math.floor(endTime*sr)),seg=padShortAudio(samples.slice(startSample,endSample)),segFrames=createFrames(seg),slice=analysis.filter(f=>f.centerTime>=startTime&&f.centerTime<=endTime);return{index:i+1,token,label,presetType:"segment",presetPath:`presets/segments/${String(i+1).padStart(3,"0")}_${label}.json`,startTime,endTime,duration:endTime-startTime,rms:rms(samples,startSample,endSample),zcr:mean(slice.map(f=>f.zcr)),spectralCentroid:mean(slice.map(f=>f.spectralCentroid)),estimatedF0:estimateF0(samples,sr,startSample,endSample),mfccMean:avgMfcc(computeMfcc(segFrames,sr)),controls:{pitchShift:0,speedRatio:1,gainDb:0,formantShift:0}}});return{segments,boundaries,candidateCount:candidates.filter(c=>c.isPeak).length-2}}
function normalizeSpectrogram(frames){return frames.map(m=>Array.from(m,v=>20*Math.log10(Math.max(v,1e-8))))}
function padShortAudio(samples){if(samples.length>=FFT_SIZE)return samples;const out=new Float32Array(FFT_SIZE);out.set(samples);return out}
function drawAxes(ctx,w,h,title,xLabel="Time",yLabel=""){ctx.fillStyle="#fbfcfb";ctx.fillRect(0,0,w,h);ctx.strokeStyle="#dbe1dc";ctx.lineWidth=1;for(let x=64;x<w-20;x+=96){ctx.beginPath();ctx.moveTo(x,40);ctx.lineTo(x,h-42);ctx.stroke()}for(let y=44;y<h-42;y+=56){ctx.beginPath();ctx.moveTo(58,y);ctx.lineTo(w-22,y);ctx.stroke()}ctx.fillStyle="#16211f";ctx.font="700 22px system-ui, sans-serif";ctx.fillText(title,58,28);ctx.font="13px system-ui, sans-serif";ctx.fillStyle="#5d6965";ctx.fillText(xLabel,w-74,h-14);if(yLabel)ctx.fillText(yLabel,10,34)}
function drawWaveform(samples,sr){const c=canvases.waveform,ctx=c.getContext("2d"),{width:w,height:h}=c;drawAxes(ctx,w,h,"Waveform","Time","Amplitude");const left=58,top=42,pw=w-82,ph=h-86,mid=top+ph/2;ctx.strokeStyle="#0f766e";ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<pw;x++){const a=Math.floor(x/pw*samples.length),b=Math.max(a+1,Math.floor((x+1)/pw*samples.length));let mn=1,mx=-1;for(let i=a;i<b;i++){mn=Math.min(mn,samples[i]);mx=Math.max(mx,samples[i])}ctx.moveTo(left+x,mid-mx*ph/2);ctx.lineTo(left+x,mid-mn*ph/2)}ctx.stroke();ctx.fillStyle="#5d6965";ctx.font="13px system-ui, sans-serif";ctx.fillText(`${(samples.length/sr).toFixed(2)} s`,w-92,h-42)}
function color(v,p="magma"){v=Math.max(0,Math.min(1,v));if(p==="mfcc")return[Math.round(35+210*v),Math.round(50+120*(1-Math.abs(v-.5)*2)),Math.round(95+145*(1-v))];return[Math.round(20+235*v),Math.round(16+135*Math.sqrt(v)),Math.round(55+65*(1-v))]}
function drawHeatmap(canvas,matrix,title,palette="magma"){const ctx=canvas.getContext("2d"),{width:w,height:h}=canvas;drawAxes(ctx,w,h,title,"Time","Frequency");const left=58,top=42,pw=w-82,ph=h-86,rows=matrix[0]?.length||1,cols=matrix.length||1;let mn=Infinity,mx=-Infinity;for(const col of matrix)for(const v of col){mn=Math.min(mn,v);mx=Math.max(mx,v)}const img=ctx.createImageData(pw,ph);for(let y=0;y<ph;y++){const r=Math.floor((1-y/ph)*(rows-1));for(let x=0;x<pw;x++){const col=Math.floor(x/pw*(cols-1)),v=(matrix[col][r]-mn)/(mx-mn||1),[rr,g,b]=color(v,palette),idx=(y*pw+x)*4;img.data[idx]=rr;img.data[idx+1]=g;img.data[idx+2]=b;img.data[idx+3]=255}}ctx.putImageData(img,left,top)}
function drawBoundaryOverlay(canvas,bounds,segments){const ctx=canvas.getContext("2d"),{width:w,height:h}=canvas,left=58,top=42,pw=w-82,ph=h-86,d=bounds.at(-1)||1;ctx.save();ctx.strokeStyle="#c2410c";ctx.fillStyle="#c2410c";ctx.lineWidth=2;ctx.font="700 14px system-ui, sans-serif";for(let i=1;i<bounds.length-1;i++){const x=left+bounds[i]/d*pw;ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+ph);ctx.stroke()}for(const s of segments){const x=left+((s.startTime+s.endTime)/2)/d*pw;ctx.fillText(s.label,x-6,top+18)}ctx.restore()}
function formatHz(v){return v?`${v.toFixed(1)} Hz`:"-"}function escapeHtml(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;")}
function renderSegmentTable(segments){segmentCount.textContent=`${segments.length} segment${segments.length===1?"":"s"}`;if(!segments.length){segmentTable.innerHTML='<tr><td colspan="9">Upload audio and enter matching text to create segments.</td></tr>';return}segmentTable.innerHTML=segments.map(s=>`<tr><td><code>${escapeHtml(s.token)}</code> / <code>${escapeHtml(s.label)}</code></td><td>${s.startTime.toFixed(3)} s</td><td>${s.endTime.toFixed(3)} s</td><td>${s.duration.toFixed(3)} s</td><td>${s.rms.toFixed(5)}</td><td>${s.zcr.toFixed(4)}</td><td>${s.spectralCentroid.toFixed(1)} Hz</td><td>${formatHz(s.estimatedF0)}</td><td>${s.mfccMean.slice(0,5).map(v=>v.toFixed(2)).join(", ")} ...</td></tr>`).join("")}
function createExperiment(audio,tokens,segments,overall){return{schemaVersion:1,goal:"Reusable voice preset research dataset",input:{audioFile:audio.fileName,transcript:transcriptInput.value,tokens},audio:{duration:audio.duration,sampleRate:audio.sampleRate,channels:audio.channels,rms:overall.rms,estimatedF0:overall.estimatedF0},segments,presetDirectories:{vowels:"presets/vowels/",consonants:"presets/consonants/",speakers:"presets/speakers/",segments:"presets/segments/"},synthesisControls:{pitchShift:"semitones",speedRatio:"1.0 is original speed",gainDb:"decibels",formantShift:"relative formant offset"}}}
function createExperimentCard(exp){const rows=exp.segments.map(s=>`| ${s.index} | ${s.token} | ${s.label} | ${s.startTime.toFixed(3)} | ${s.endTime.toFixed(3)} | ${s.rms.toFixed(5)} | ${s.zcr.toFixed(4)} | ${s.spectralCentroid.toFixed(1)} | ${s.estimatedF0?s.estimatedF0.toFixed(1):"-"} | ${s.mfccMean.slice(0,5).map(v=>v.toFixed(2)).join(", ")} |`).join("\n");return`# Experiment 001\n\n## Input\n\n- Audio: ${exp.input.audioFile}\n- Text: ${exp.input.transcript}\n- Duration: ${exp.audio.duration.toFixed(3)} s\n- Sample rate: ${exp.audio.sampleRate} Hz\n- RMS: ${exp.audio.rms.toFixed(5)}\n- Estimated F0: ${exp.audio.estimatedF0?`${exp.audio.estimatedF0.toFixed(1)} Hz`:"-"}\n- Estimated boundary count: ${exp.segmentation.estimatedBoundaryCount}\n- Mora count: ${exp.segmentation.moraCount}\n\n## Analysis Images\n\n- Waveform: \`waveform.png\`\n- Spectrogram: \`spectrogram.png\`\n- MFCC: \`mfcc.png\`\n\n## Segment Features\n\n| # | Token | Label | Start | End | RMS | ZCR | Centroid | F0 | MFCC mean first 5 |\n|---|---|---|---:|---:|---:|---:|---:|---:|---|\n${rows||"| - | - | - | - | - | - | - | - | - | - |"}\n\n## Notes\n\n- This is signal-based segmentation, not speech recognition.\n- Boundaries are inferred from silence, RMS drops, MFCC change, and spectral change.\n- When boundary count and mora count differ, candidate boundaries are aligned to mora count with balance constraints.\n`}
function downloadTextFile(name,content,type){const blob=new Blob([content],{type}),a=document.createElement("a");a.download=name;a.href=URL.createObjectURL(blob);a.click();URL.revokeObjectURL(a.href)}
function redrawBase(){drawWaveform(currentAudio.samples,currentAudio.sampleRate);drawHeatmap(canvases.spectrogram,normalizeSpectrogram(currentAudio.frames),"Spectrogram","magma");drawHeatmap(canvases.mfcc,computeMfcc(currentAudio.frames,currentAudio.sampleRate),"MFCC","mfcc")}
function updateResearchOutputs(){if(!currentAudio)return;const tokens=tokenizeTranscript(transcriptInput.value);if(!tokens.length){currentExperiment=null;meta.boundaryCount.textContent="-";meta.moraCount.textContent="0";renderSegmentTable([]);redrawBase();return}const seg=extractSegmentFeatures(currentAudio.samples,currentAudio.sampleRate,currentAudio.duration,tokens),overall={rms:rms(currentAudio.samples),estimatedF0:estimateF0(currentAudio.samples,currentAudio.sampleRate)};currentExperiment=createExperiment(currentAudio,tokens,seg.segments,overall);currentExperiment.segmentation={method:"signal-boundary-candidates-with-mora-alignment",estimatedBoundaryCount:seg.candidateCount,moraCount:tokens.length,boundaries:seg.boundaries};meta.boundaryCount.textContent=String(seg.candidateCount);meta.moraCount.textContent=String(tokens.length);renderSegmentTable(seg.segments);redrawBase();drawBoundaryOverlay(canvases.waveform,seg.boundaries,seg.segments);drawBoundaryOverlay(canvases.spectrogram,seg.boundaries,seg.segments);drawBoundaryOverlay(canvases.mfcc,seg.boundaries,seg.segments)}
async function analyzeFile(file){setStatus("Loading","busy");const buf=await file.arrayBuffer(),ctx=new AudioContext(),audio=await ctx.decodeAudioData(buf);if(audio.duration>MAX_AUDIO_SECONDS)throw new Error(`Audio is ${audio.duration.toFixed(1)}s. Please use audio up to ${MAX_AUDIO_SECONDS}s.`);const samples=padShortAudio(mixToMono(audio));meta.fileName.textContent=file.name;meta.duration.textContent=formatDuration(audio.duration);meta.sampleRate.textContent=`${audio.sampleRate.toLocaleString()} Hz`;meta.channels.textContent=String(audio.numberOfChannels);const overallRms=rms(samples),overallF0=estimateF0(samples,audio.sampleRate);meta.rms.textContent=overallRms.toFixed(5);meta.f0.textContent=formatHz(overallF0);currentAudio={fileName:file.name,samples,duration:audio.duration,sampleRate:audio.sampleRate,channels:audio.numberOfChannels,frames:createFrames(samples)};setStatus("Analyzing","busy");await new Promise(r=>setTimeout(r,20));redrawBase();await ctx.close();updateResearchOutputs();setStatus("Complete","done")}
function handleFiles(files){const file=files?.[0];if(!file)return;analyzeFile(file).catch(err=>{console.error(err);setStatus("Error","busy");alert(`Could not analyze this file: ${err.message}`)})}
fileInput.addEventListener("change",e=>handleFiles(e.target.files));transcriptInput.addEventListener("input",updateResearchOutputs);dropZone.addEventListener("dragover",e=>{e.preventDefault();dropZone.classList.add("dragging")});dropZone.addEventListener("dragleave",()=>dropZone.classList.remove("dragging"));dropZone.addEventListener("drop",e=>{e.preventDefault();dropZone.classList.remove("dragging");handleFiles(e.dataTransfer.files)});
document.querySelectorAll("[data-canvas]").forEach(btn=>btn.addEventListener("click",()=>{const c=$(`#${btn.dataset.canvas}`),a=document.createElement("a");a.download=`${btn.dataset.canvas.replace("-canvas","")}.png`;a.href=c.toDataURL("image/png");a.click()}));downloadJson.addEventListener("click",()=>currentExperiment&&downloadTextFile("presets_segments_experiment_001.json",JSON.stringify(currentExperiment,null,2),"application/json"));downloadCard.addEventListener("click",()=>currentExperiment&&downloadTextFile("Experiment_001.md",createExperimentCard(currentExperiment),"text/markdown"));
drawAxes(canvases.waveform.getContext("2d"),canvases.waveform.width,canvases.waveform.height,"Waveform");drawAxes(canvases.spectrogram.getContext("2d"),canvases.spectrogram.width,canvases.spectrogram.height,"Spectrogram");drawAxes(canvases.mfcc.getContext("2d"),canvases.mfcc.width,canvases.mfcc.height,"MFCC");
